### ISSUE TITLE
When will the source code be released?

### ISSUE THREAD

**Issue by guijiql** [mdyx/ARD#2]
Hi, I am reading your paper and it's an interesting work.
I understand you might be busy these days. Could you please provide an approximate time of releasing the code? I have difficulties in reproducing the results. Thank you.

**Comment by mdyx** [comment]
Hi! Thank you for your interest. 
I'm very busy these days and I may need some time to tidy the code as the code was completed over a year ago. I will let you know as soon as the code is released.

**Comment by guijiql** [comment]
Thanks for your reply! I understand that tidying code is a complex work. 

If it's not troublesome to you, could you please show the model file (model.py) and the code segment that predicts the next item first? 
If not, only the latter is fine as well. 

It doesn't matter if the code can't be run or there are no comments. It's also OK that sending the file via email. Thank you!

**Comment by mdyx** [comment]
Hello! The implementation details have been replied to you, I hope that will help you.

**Comment by Hughlhz** [comment]
作者您好，我最近有幸拜读了您精彩的论文，我对aspect-redistribution那一块非常感兴趣，但是还有些疑惑。
请问你可以告诉我更多关于实现那一部分的细节吗？能像上面那样发一份model.py的文件最好了hhhh
万分感谢！

**Comment by mdyx** [comment]
@Hughlhz 您好！
非常感谢您的关注，但是我不知道您的邮箱地址是多少。
可以告知一下您的邮箱地址或者用您的邮箱随便发个邮件给我吗。
再次感谢

**Comment by Hughlhz** [comment]
感谢您的回复，我的邮箱是hughes.lhz@gmail.com
> @Hughlhz 您好！
> 
> 非常感谢您的关注，但是我不知道您的邮箱地址是多少。
> 
> 可以告知一下您的邮箱地址或者用您的邮箱随便发个邮件给我吗。
> 
> 再次感谢

**Comment by XiHuangTKDG** [comment]
作者您好，我最近也拜读了您的论文，对其中的实现细节非常感兴趣。请问可以像上面的一样用邮件发一份 model.py 的文件给我看看吗？我的邮箱是 james_huang@mail.ustc.edu.cn
不胜感激！

**Comment by clcron** [comment]
作者您好，我最近也拜读了您的论文，对其中的实现细节非常感兴趣。请问可以像上面的一样用邮件发一份 model.py 的文件给我看看吗？我的邮箱是[clcron@foxmail.com](clcron@foxmail.com)  
不胜感激！
